### ISSUE TITLE
need to modify the group of /bin/usr ?!?!?!?

### ISSUE THREAD

**Issue by sbibayoff** [learn-co-curriculum/welcome-to-learn-4#2]
Was just going trough the instructions on setting up Learn IDE on Linux:
[https://learn.co/manual_setup](https://learn.co/manual_setup)
Step 6 has:

```
sudo chown root:staff /usr/bin
sudo chmod 0775 /usr/bin
```

Really???? You see nothing wrong with this?

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
